import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { Resend } from "resend";

export const maxDuration = 30;

const SYSTEM_PROMPT = `You are an elite sales coach for Gushwork, an AEO (Answer Engine Optimization) company that helps B2B businesses show up in AI search engines like ChatGPT, Perplexity, and Gemini.

You listen to AE call transcripts and deliver one sharp, direct coaching insight. No fluff. No praise sandwich. Lead with the miss.

You score the call on these dimensions:
- AEO explanation clarity — did the AE explain SEO vs AEO simply enough for a non-technical SMB owner
- ROI timeline handling — did they set correct expectations (3-4 months to compound) without losing the prospect
- Objection handling — "why not an SEO agency", "I already have a website", "my nephew does our marketing"
- Credibility establishment — did they use specific Gushwork case studies and numbers
- Next step clarity — did the call end with a clear committed next step or did it fizzle into "I'll send you some info"

Find the single biggest miss on the call. Be direct and specific. Reference the exact moment it went wrong. Then tell the AE exactly what to say instead.

When coaching on credibility, reference real Gushwork case studies the AE should have used:
- Source Equipment: 40+ qualified leads per month from Google and AI search
- John Maye Company: 120+ leads in 4 months
- Fraxtional: $500K ARR directly attributed to Gushwork
- Denver skincare manufacturer: nearly churned on day 3, 12-15 qualified leads per month by day 60

Output format: 3-4 sentences max. Start with the miss. Be specific about the moment. Tell them exactly what to say next time. No bullet points. No score. Just straight talk like a great sales manager who just listened to your call.`;

export async function POST(req: NextRequest) {
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const resend = new Resend(process.env.RESEND_API_KEY);

  try {
    const { transcript } = await req.json();

    if (!transcript || typeof transcript !== "string" || transcript.trim().length < 50) {
      return NextResponse.json(
        { error: "Transcript is too short or missing." },
        { status: 400 }
      );
    }

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: `Here is the sales call transcript:\n\n${transcript.trim()}`,
        },
      ],
      temperature: 0.7,
      max_tokens: 300,
    });

    const insight = completion.choices[0]?.message?.content?.trim();

    if (!insight) {
      return NextResponse.json(
        { error: "No insight returned from OpenAI." },
        { status: 500 }
      );
    }

    // Send email via Resend (non-blocking — don't fail the request if email fails)
    resend.emails.send({
      from: "AE Coach <onboarding@resend.dev>",
      to: "hritik01kumar@gmail.com",
      subject: "Your Sales Call Coaching Insight",
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 32px; background: #09090b; color: #f4f4f5; border-radius: 12px;">
          <p style="font-size: 11px; font-weight: 600; letter-spacing: 0.1em; color: #818cf8; text-transform: uppercase; margin-bottom: 8px;">Gushwork · AEO Sales</p>
          <h1 style="font-size: 20px; font-weight: 700; margin-bottom: 24px; color: #f4f4f5;">AE Performance Coach</h1>
          <p style="font-size: 15px; line-height: 1.7; color: #e4e4e7;">${insight}</p>
          <hr style="border: none; border-top: 1px solid #27272a; margin: 32px 0;" />
          <p style="font-size: 12px; color: #52525b;">Generated by AE Performance Coach · Powered by GPT-4o</p>
        </div>
      `,
    }).catch(console.error);

    return NextResponse.json({ insight });
  } catch (err) {
    console.error("Analyze error:", err);
    return NextResponse.json(
      { error: "Failed to analyze transcript. Check your API keys." },
      { status: 500 }
    );
  }
}
